"""add delivery fee and grand total

Revision ID: 09728578d17a
Revises: ed064e43b4bf
Create Date: 2026-10-07 21:23:37.156576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09728578d17a'
down_revision: Union[str, Sequence[str], None] = 'ed064e43b4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=10, scale=1), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('grand_total', sa.Numeric(precision=10, scale=1), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'grand_total')
    op.drop_column('orders', 'delivery_fee')
    # ### end Alembic commands ###
