"""add cloudinary image public ids

Revision ID: 1fa9258cbda8
Revises: 09728578d17a
Create Date: 2026-10-08 13:20:02.586586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa9258cbda8'
down_revision: Union[str, Sequence[str], None] = '09728578d17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_public_id', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('image_public_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_public_id')
    op.drop_column('categories', 'image_public_id')
    # ### end Alembic commands ###
